# ── Daily Briefing (Nate's Format) ────────────────────────────────────────────

DAILY_BRIEFING_SYSTEM = """You are a competitive intelligence analyst for RivalEdge. Generate a daily competitive briefing.

CRITICAL RULES:
1. Do NOT summarize competitors
2. Focus ONLY on what changed or is different
3. Every insight must include: Clear observation → Business implication → Recommended action
4. Avoid generic statements

OUTPUT FORMAT (STRICT):

RIVALEDGE DAILY BRIEFING
Company: [Prospect Name]
Date: [Use the date provided in the prompt]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

HIGH IMPACT

Competitor: [Name]
Observation:
[Specific change or difference - be concrete]

Why it matters:
[Concrete impact on conversion, positioning, or revenue]

Recommended action:
[Clear, immediate step the prospect should take]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

MEDIUM IMPACT

Competitor: [Name]
Observation:
[Specific change or difference]

Why it matters:
[Business impact]

Recommended action:
[Clear step]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ADDITIONAL SIGNALS

• Competitor X: [Positioning shift toward segment/feature]
• Competitor Y: [Emphasizing specific value prop]
• [Any other notable competitive movements]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUMMARY

• Competitors analyzed: [2-3]
• Key risks: [1-2 bullets]
• Key opportunities: [1-2 bullets]

First line must be: <!-- SUBJECT: RivalEdge Daily Brief - [Date] -->
Use inline CSS, max-width 600px, dark background (#0f172a), white text, mobile-responsive.
Footer with: {{unsubscribe_url}} placeholder"""


def generate_daily_briefing(user_email: str, company_name: str, competitors_with_diffs: list[dict]) -> str:
    """
    Generate a daily competitive briefing using Nate's format.
    Focuses on what changed and actionable recommendations.
    """
    from datetime import datetime
    
    # Get current date
    current_date = datetime.now().strftime("%B %d, %Y")
    
    # Categorize by significance
    high_impact = []
    medium_impact = []
    additional_signals = []
    
    for comp in competitors_with_diffs:
        comp_name = comp.get('competitor_name', 'Unknown')
        diff_result = comp.get('diff_result', {})
        changes = diff_result.get('changes', [])
        
        # Get profile info for context
        profile = comp.get('current_profile', '')
        if isinstance(profile, dict):
            positioning = profile.get('positioning', '')
            pricing = profile.get('pricing', '')
            features = profile.get('features', [])
        else:
            positioning = ''
            pricing = ''
            features = []
        
        # Categorize changes
        for change in changes:
            significance = change.get('significance', 'low')
            field = change.get('field', '')
            change_type = change.get('type', 'changed')
            old_val = change.get('old_value', '')
            new_val = change.get('new_value', '')
            
            change_info = {
                'competitor': comp_name,
                'field': field,
                'type': change_type,
                'old': old_val,
                'new': new_val,
                'positioning': positioning,
                'pricing': pricing,
                'features': features
            }
            
            if significance == 'high':
                high_impact.append(change_info)
            elif significance == 'medium':
                medium_impact.append(change_info)
        
        # Add positioning shifts as additional signals
        if positioning:
            additional_signals.append({
                'competitor': comp_name,
                'signal': f"Positioning: {positioning[:100]}..."
            })
    
    # Format high impact changes
    high_impact_text = ""
    if high_impact:
        for item in high_impact:
            high_impact_text += f"""
Competitor: {item['competitor']}
Observation:
{item['field'].upper()} {item['type'].upper()}: {item['old'][:50] if item['old'] else 'N/A'} → {item['new'][:50] if item['new'] else 'N/A'}

Why it matters:
[To be generated by AI based on field type and values]

Recommended action:
[To be generated by AI]

"""
    else:
        high_impact_text = "No high-impact changes detected today."
    
    # Format medium impact changes
    medium_impact_text = ""
    if medium_impact:
        for item in medium_impact[:3]:  # Limit to top 3
            medium_impact_text += f"""
Competitor: {item['competitor']}
Observation:
{item['field'].upper()} {item['type'].upper()}: {item['old'][:50] if item['old'] else 'N/A'} → {item['new'][:50] if item['new'] else 'N/A'}

Why it matters:
[To be generated by AI]

Recommended action:
[To be generated by AI]

"""
    else:
        medium_impact_text = "No medium-impact changes detected today."
    
    # Format additional signals
    signals_text = ""
    if additional_signals:
        for signal in additional_signals[:5]:
            signals_text += f"• {signal['competitor']}: {signal['signal']}\n"
    else:
        signals_text = "• No significant positioning shifts detected."
    
    prompt = f"""Generate a daily competitive briefing for {company_name}.

CURRENT DATE: {current_date}

HIGH IMPACT CHANGES:
{high_impact_text}

MEDIUM IMPACT CHANGES:
{medium_impact_text}

ADDITIONAL COMPETITIVE SIGNALS:
{signals_text}

Generate the complete HTML email following the DAILY BRIEFING format. Be specific, actionable, and concise. Focus on what changed and why it matters."""
    
    return _call_ai(
        system=DAILY_BRIEFING_SYSTEM,
        user=prompt,
        max_tokens=4000,
        use_cache=False,
    )


# ── Token Usage Monitoring (Stub functions for ai_monitor router) ─────────────

def get_token_usage_stats(days: int = 7) -> dict:
    """
    Get AI token usage statistics for the specified period.
    Stub implementation - returns empty stats.
    """
    return {
        "total_requests": 0,
        "total_tokens": 0,
        "total_cost": 0.0,
        "by_model": {},
        "by_day": [],
        "note": "Token tracking not yet implemented"
    }


def audit_context_efficiency() -> dict:
    """
    Audit context management efficiency.
    Stub implementation - returns basic info.
    """
    return {
        "status": "ok",
        "context_hits": 0,
        "context_misses": 0,
        "efficiency_score": 1.0,
        "note": "Context efficiency tracking not yet implemented"
    }


def get_model_info(model: str = None) -> dict:
    """
    Get information about available AI models.
    Stub implementation - returns basic model info.
    """
    models = {
        "kimi-k2.5": {
            "name": "Kimi K2.5",
            "provider": "moonshot",
            "cost_per_1k_input": 0.0001,
            "cost_per_1k_output": 0.0002,
        },
        "claude-sonnet": {
            "name": "Claude Sonnet",
            "provider": "anthropic",
            "cost_per_1k_input": 0.003,
            "cost_per_1k_output": 0.015,
        }
    }
    
    if model and model in models:
        return models[model]
    return models


def research_lead(prompt: str, max_tokens: int = 500) -> str:
    """
    Use AI to research a lead and return structured insights.

    Args:
        prompt: The research prompt (e.g. asking for pain signals)
        max_tokens: Maximum tokens for the response

    Returns:
        AI response as a string, or "[]" if the call fails
    """
    try:
        return _call_ai(
            system="You are a sales research assistant. Analyze leads and identify pain signals.",
            user=prompt,
            max_tokens=max_tokens,
            use_cache=False,
        )
    except Exception:
        return "[]"
