export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-slate-400 mb-8">Last updated: April 1, 2026</p>

        <div className="prose prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-300">By accessing or using RivalEdge (&quot;the Service&quot;) at rivaledge.ai, operated by Aether Holding LLC (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">2. Description of Service</h2>
            <p className="text-slate-300">RivalEdge provides automated competitive intelligence by monitoring publicly available information on competitor websites specified by you. We deliver AI-generated weekly summaries of changes to pricing, features, and messaging.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">3. Acceptable Use</h2>
            <p className="text-slate-300">You agree to use RivalEdge only for lawful purposes. You may not:</p>
            <ul className="text-slate-300 space-y-2 list-disc list-inside mt-2">
              <li>Use the Service to monitor private, non-public information</li>
              <li>Attempt to circumvent authentication or access controls on third-party sites</li>
              <li>Resell or redistribute data generated by the Service without permission</li>
              <li>Use the Service to harass, defame, or harm any individual or business</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">4. Subscriptions and Billing</h2>
            <p className="text-slate-300">RivalEdge offers paid subscription plans (Solo at $49/month, Pro at $99/month). By subscribing, you authorize us to charge your payment method on a recurring basis. You may cancel at any time. Refunds are handled on a case-by-case basis — contact support@rivaledge.ai within 7 days of a charge for assistance.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">5. Free Trial</h2>
            <p className="text-slate-300">We offer a 14-day free trial. No credit card is required to start. If you add a payment method, you will be charged at the end of the trial period unless you cancel first.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">6. Intellectual Property</h2>
            <p className="text-slate-300">The RivalEdge platform, software, and AI-generated content are owned by Aether Holding LLC. Data you input (competitor URLs, account information) remains yours. We do not claim ownership of third-party content we monitor on your behalf.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">7. Disclaimer of Warranties</h2>
            <p className="text-slate-300">The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that competitive intelligence gathered is complete, accurate, or up to date. Use the Service as one input among many in your business decisions.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">8. Limitation of Liability</h2>
            <p className="text-slate-300">To the maximum extent permitted by law, Aether Holding LLC shall not be liable for any indirect, incidental, or consequential damages arising from your use of RivalEdge. Our total liability shall not exceed the amount you paid us in the 3 months preceding any claim.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">9. Termination</h2>
            <p className="text-slate-300">We reserve the right to suspend or terminate your account for violation of these Terms. You may cancel your account at any time by contacting support@rivaledge.ai.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">10. Governing Law</h2>
            <p className="text-slate-300">These Terms are governed by the laws of the State of Illinois, United States. Any disputes shall be resolved in the courts of Cook County, Illinois.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">11. Changes to Terms</h2>
            <p className="text-slate-300">We may update these Terms from time to time. We will notify you by email or in-app notice. Continued use after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">12. Contact</h2>
            <p className="text-slate-300">Questions about these Terms? Contact us at: <a href="mailto:support@rivaledge.ai" className="text-blue-400 hover:underline">support@rivaledge.ai</a></p>
            <p className="text-slate-300 mt-2">Aether Holding LLC · Buffalo Grove, IL 60089</p>
          </section>
        </div>
      </div>
    </div>
  );
}
